manifest.php, scripts/update/Updater.php, views/js/review/plugins/navigation/next-prev/plugin.js, views/js/review/provider/qtiTestReviewProvider.js
Related to: https://oat-sa.atlassian.net/browse/TAO-8721
Fix the navigation broken since the update on the test runner API.
Impacted unit test:
- `taoReview/views/js/test/review/provider/qtiTestReviewProvider/test.html`
- `taoReview/views/js/test/review/plugins/navigation/next-prev/plugin/test.html`
- `taoReview/views/js/test/review/plugins/navigation/review-panel/plugin/test.html`
To launch tests:
```
cd tao/views/build
npx grunt connect:dev taoreviewtest
```
=> Fix/tao 8721/update navigation

manifest.php, scripts/update/Updater.php, views/js/review/plugins/navigation/next-prev/plugin.js, views/js/review/plugins/navigation/review-panel/plugin.js, views/js/review/provider/qtiTestReviewProvider.js, views/js/review/services/navigator.js, views/js/test/review/component/qtiTestReviewComponent/test.js, views/js/test/review/plugins/navigation/next-prev/plugin/test.html, views/js/test/review/plugins/navigation/next-prev/plugin/test.js, views/js/test/review/plugins/navigation/review-panel/plugin/test.js, views/js/test/review/provider/qtiTestReviewProvider/test.html, views/js/test/review/provider/qtiTestReviewProvider/test.js, views/js/test/review/services/navigator/test.html, views/js/test/review/services/navigator/test.js, views/js/test/review/services/navigator/testContexts.json, views/js/test/review/services/navigator/testMap.json, views/js/test/review/services/navigator/testMapFiltered.json
Related to: https://oat-sa.atlassian.net/browse/TAO-8928
Make the navigator service compatible with filtered test maps.
As the jumps table might contains gaps when the test maps is filtered, the navigator service must be able to jump over those gaps while moving forward and backward along the test.
The navigator service supplied by the test runner has been extended.
The test runner is also now emitting a `testmapchange` event each time the test map get updated. This allows the plugins to adapt their UI accordingly.
Impacted unit test:
- `taoReview/views/js/test/review/component/qtiTestReviewComponent/test.html`
- `taoReview/views/js/test/review/plugins/navigation/next-prev/plugin/test.html`
- `taoReview/views/js/test/review/plugins/navigation/review-panel/plugin/test.html`
- …
=> Feature/tao 8928/make navigator support filtered jumps table

controller/Review.php, manifest.php, models/DeliveryExecutionFinderService.php, scripts/update/Updater.php
Task https://oat-sa.atlassian.net/browse/TAO-8942
Depends on https://github.com/oat-sa/extension-tao-testqti-previewer/pull/33
This PR include the next changes:
- now it requires `taoQtiTestPreviewer` extension as it called inside.
- correct responses fetched from compiled data and merged with item definition.
- changed the way of getting results. Now GET parameter `execution` has higher priority than `lis_result_sourcedid`, but the latest still work to keep backward compatibility.
How to test: run any test and after that, using LTI tools, run it in the review mode and set custom parameter `show_correct` as `true` or `1`.
=> Add correct item responses from previewer

config/default/DeliveryExecutionFinderService.conf.php, manifest.php, models/DeliveryExecutionFinderService.php, scripts/update/Updater.php, test/unit/model/DeliveryExecutionFinderServiceTest.php
Related to: https://oat-sa.atlassian.net/browse/TAO-9038
Add platform options for the LTI custom parameters controlling the disclosure of the scores and the correct responses.
Impacted unit test: `ltiTestReview/test/unit/model/DeliveryExecutionFinderServiceTest.php`
Platform options available in the config file `ltiTestReview/config/default/DeliveryExecutionFinderService.conf.php`:
```php
return new \oat\ltiTestReview\models\DeliveryExecutionFinderService([
'show_score' => false,
'show_correct' => false
]);
```
=> Feature/tao 9038/add platform options

controller/Review.php, manifest.php, scripts/update/Updater.php
Related to: https://oat-sa.atlassian.net/browse/TAO-8942
Requires: 
Move the responses data filtering into the `getItem` endpoint. The reason why is we need all the consolidated data in order to properly discard incompatible entries.
=> Fix/tao 8942/filter responses data

controller/Review.php, manifest.php, scripts/update/Updater.php
Related to: https://oat-sa.atlassian.net/browse/TAO-8942
An error was on the filtering for responses data. The returned responses were emptied because the filter condition was not targeting the right context.
=> Fix/tao 8942/error in filter for responses data

manifest.php, scripts/update/Updater.php
If taoProctring is not installed usage of ltiTestReview will raise 500 error due to service not found. 
This update requires taoProctoring during installation of ltiTestReview extension.
=> Require taoProctoring due to usage of functions from this extension

manifest.php, scripts/update/Updater.php
https://oat-sa.atlassian.net/browse/BOSA-23
It is already required on the showroom, but it should be fixed in the code.
=> Require LTI Proctoring extension

manifest.php, models/QtiRunnerInitDataBuilder.php, scripts/update/Updater.php
Without the fix, it brokes FE when showing notices enabled in PHP. It happens when custom parameters about showing scores (custom_show_score) set to false because in this case score and max score not provided. By default custom parameters are set as false.
=> Avoid notices when scores not provided

manifest.php, models/DeliveryExecutionFinderService.php
- [BSA-192](https://oat-sa.atlassian.net/browse/BSA-192) fix: stop using deprecated `oat\taoDelivery\model\execution\Service`
- [BSA-192](https://oat-sa.atlassian.net/browse/BSA-192) chore(version): bump a fix one
=> Fix BSA-192 stop using deprecated execution service interface

controller/Review.php, manifest.php, test/unit/model/DeliveryExecutionFinderServiceTest.php, views/js/test/review/services/navigator/test.js
The task is [BSA-104](https://oat-sa.atlassian.net/browse/BSA-104)
Before the fix, action `getItem` returned feedbacks in two places. One by the path `data/feedbacks`, and the second one in the responses as a usual response. Because the QTI loader tried to load it twice, it triggered error that such an item already exists.
I removed feedback from the responses, to give the ability to load them independently from the `data/feedbacks` source.
=> Remove feedback entries from responses

controller/Review.php, manifest.php, views/js/review/proxy/qtiTestReviewProxy.js, views/js/test/review/proxy/qtiTestReviewProxy/test.js
- [TBD-45](https://oat-sa.atlassian.net/browse/TBD-45) feat: stop verifying a request CSRF token upon handling requests, retrieving review items
- [TBD-45](https://oat-sa.atlassian.net/browse/TBD-45) feat: stop sending CSRF tokens to GET review item request handlers
- [TBD-45](https://oat-sa.atlassian.net/browse/TBD-45) chore(version): bump a minor one
=> Feature TBD-45 do not perform csrf token validation on get request handling

composer.json, controller/ReviewTool.php, manifest.php, migrations/Version2021092101_ltiTestReview.php
Related to: https://oat-sa.atlassian.net/browse/TR-1910
Need to merge it first https://github.com/oat-sa/extension-tao-lti/pull/305
Need to provide delivery execution id in custom claims.
Example for NG stack.
Launch URL: `http://backoffice.docker.localhost/ltiTestReview/ReviewTool/launch1p3`
```
{
"https://purl.imsglobal.org/spec/lti/claim/roles": [
"http://purl.imsglobal.org/vocab/lis/v2/membership#Learner"
],
"https://purl.imsglobal.org/spec/lti/claim/custom": {
"execution": "http://backoffice.docker.localhost/ontologies/tao.rdf#i6149ccf3252db7e59ff53bc7c1bcfc",
"custom_show_score": "true",
"custom_show_correct": "true"
}
}
```
DevKit Link
http://lti.docker.localhost/platform/message/launch/lti-resource-link?registration=devkitToTAO&user_list=c3po&launch_url=http://backoffice.docker.loc …
=> feat: added new endpoint for LTI1p3 review mode

composer.json
https://oat-sa.atlassian.net/browse/TR-1966
**extension-lti-outcomeui was deleted**
How to test it
1. Install [Bosa's composer.json packages](https://github.com/oat-sa/tao-enterprise-bosa/blob/v0.148.2-alpha/composer.json)
2. Run taoSetup (docker exec -it nextgen_tao_phpfpm php tao/scripts/taoSetup.php setup.json -vvv)
3. Install ltiTestReview in the backoffice
4. Install [the next composer's packages](https://github.com/oat-sa/extension-lti-test-review/files/7253284/composer.zip) (including repositories) 
5. Run taoUpdate (php tao/scripts/taoUpdate.php (inside nextgen_tao_phpfpm container ) )
=> fix: remove oat-sa/extension-lti-outcomeui dependency

README.md, composer.json, controller/Review.php, controller/ReviewTool.php, manifest.php, migrations/Version202111031413133291_ltiTestReview.php, models/DeliveryExecutionFinderService.php, test/unit/model/DeliveryExecutionFinderServiceTest.php
Context about running review mode by `userId` and `deliveryId` without usage of `executionId` in claim set
* install current branch version of package in `tao` on `nextgen-stack`
* start delivery with specified userId on a `tao` used as a tool with resource_link claim. For example 
```
"https://purl.imsglobal.org/spec/lti/claim/resource_link": {
"id": "local_devkit_1"
}
```
* run review mode for specified userId with deliveryId with next set of claims 
```
{
"https://purl.imsglobal.org/spec/lti/claim/roles": [
"http://purl.imsglobal.org/vocab/lis/v2/membership#Learner"
],
"https://purl.imsglobal.org/spec/lti/claim/custom": {
"custom_show_score": "true",
"custom_show_correct": "true"
},
"https://purl.imsglobal.org/spec/lti/claim/for_user": {
"user_id": "<string>",
}, …
```
=> Feature/tr 1919/lti submission review request

README.md, controller/Review.php, models/DeliveryExecutionFinderService.php, test/unit/model/DeliveryExecutionFinderServiceTest.php
Add support `https://purl.imsglobal.org/spec/lti/claim/resource_link` in submission review request to specify request delivery execution.
- install branch
- launch delivery execution by lti 1.3 with resource_link claim
```
...
"https://purl.imsglobal.org/spec/lti/claim/resource_link": {
"id": "unique_Id"
}
...
```
- launch review with [SubmissionReviewRequestMessage](https://github.com/oat-sa/extension-lti-test-review/blob/master/README.md#lti-calls) with the same claim 
```
...
"https://purl.imsglobal.org/spec/lti/claim/resource_link": {
"id": "unique_Id"
}
...
```
[review request example](http://devkit.docker.localhost/platform/message/launch/submission-review?registration=backofficeToolRegistration&user_list=c3po&ags_scopes%5B0%5D=https://purl.imsglobal.org/spec/lti-ags/scope/score&ags_ …
=> Specify request for review execution by `resource link id`

views/js/review/plugins/content/item-answer/plugin.js
Related to: https://oat-sa.atlassian.net/browse/TR-4504
Depends on: https://github.com/oat-sa/tao-item-runner-qti-fe/pull/317
- Create item with Math PCI, set answer in Response
- Create Delivery, run it by lti tool
- Set right answer in Math PCI
- Run review by lti tool
- Check that Math PCI is has right answer
- Create item with Math PCI, don not set answer in Response
- Create Delivery, run it by lti tool
- Set right answer in Math PCI
- Run review by lti tool
- Check that Math PCI is has wrong answer
=> feat: use mapEntries for correct response

controller/Review.php
**Associated Jira issue:** [INF-262](https://oat-sa.atlassian.net/browse/INF-262)
Make sure the pause reason associated to a delivery execution is cleared as soon as the execution is (re)started. Otherwise, once the test taker completes the test, the pause reason is still there, which makes the test runner to show a page stating that the test was "paused due to a concurrent session" instead of finished normally.
[INF-262]: https://oat-sa.atlassian.net/browse/INF-262?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Clear the pause reason for the test being restarted

views/js/review/plugins/content/item-answer/item-answer.js, views/js/review/plugins/content/item-answer/plugin.js, views/js/test/review/plugins/content/item-answer/item-answer/test.js, views/js/test/review/plugins/content/item-answer/plugin/test.js
Related to https://oat-sa.atlassian.net/browse/INF-263
If claims were `showCorrect=true` & `showScore=false`, then "_Correct response_" tab was never shown. But it should be shown.
[Launch link example](https://devkit-oat-dev.dev.gcp-eu.taocloud.org/platform/message/launch/submission-review?registration=Kitchen%20Tool&user_list=c3po&ags_scopes%5B0%5D=https://purl.imsglobal.org/spec/lti-ags/scope/lineitem&ags_line_item_url=test&for_user_type=other&for_user_id=test_unanswered&for_user_name=test_unanswered&submission_review_url=https://lti1p3-platform.playground.kitchen.it.taocloud.org/ltiTestReview/ReviewTool/launch1p3?delivery%3Dhttps%253A%252F%252Flti1p3-platform.playground.kitchen.it.taocloud.org%252Ftao.rdf%2523i6572f1826f324185ecffd6a2e7b90783&claims=%7B%0D%0A%20%20%20%20%22https://purl …
=> Fix/inf 263/item answer showcorrect but no showscore

views/js/review/services/navigation-data.js
A unit test was hanging, and failing:
Problem is visible in CI action since 3 months: https://github.com/oat-sa/extension-lti-test-review/actions/workflows/continuous-integration.yaml
This coincides with the lodash upgrade from 2 -> 4, even though no change was made in this repo at the time, it should have been.
`_.pick(function)` must become `_.pickBy(function)`. [Docs](https://lodash.com/docs/4.17.15#pickBy).
Test now passes again, with `npx grunt connect:test ltitestreviewtest`
=> Fix: pick becomes pickBy with lodash 4
